### ISSUE TITLE
Issue with `embed-resources: true` and shinylive

### ISSUE THREAD

**Issue by muellerzr** [quarto-ext/shinylive#12]
Hi all!

Love the project :)

Hit a fun snag when I was getting a recent blog up and going where if `embed-resources:true` is set in my `_quarto.yml`, shinylive just won't render!

Minimal repr:

YAML:
```yaml
project:
  type: website
format:
  html:
    css: styles.css
    embed-resources: true
```
`somepage.qmd`:
```markdown
# A test

```{shinylive-python}
#| components: [editor, terminal]

def hello_world():
  "Something that prints Hello World"
  return "Hello World"
 

hello_world()
```
```

Result:
![image](https://github.com/quarto-ext/shinylive/assets/7831895/25fa9e44-bd71-41c8-a916-8aee0c891933)

Whereas normally I'd expect a shinylive app to be there!

Note that if I *don't* have `embed-resources`, it works fine :) Thanks!
